config/routes.rb
Rails.application.routes.draw do

  root to: redirect('/categories')

  resources :addons,       only: [:index, :show]
  resources :categories,   only: [:index, :show]
  resources :contributors, controller: 'users', only: [:index]

  get "contributors/:login",      to: "users#show",                        as: :contributor
  get "freshest",                 to: "addons#index",    sort: "freshest", as: :freshest
  get "popular",                  to: "addons#index",    sort: "popular",  as: :popular
  get "unsorted",                 to: "unsorteds#index",                   as: :unsorted

  get "/auth/:provider/callback", to: "sessions#create"
  get "/logout",                  to: "sessions#destroy",                  as: :logout

  namespace :admin do
    resources :repos, only: [:index, :update]
  end

  constraints(format: 'json') do
    get "/api/v1/search", to: "apis#search1"
    get "/api/v1/users/:login", to: "apis#user1"
    get "/api/v1/users/:login/repos", to: "apis#user_repos1"
    get "/api/v1/users/:login/repos/:repo_name", to: "apis#user_repo1"
    get "/api/v1/repos", to: "apis#repos1"
    get "/api/v1/repos/:repo_name", to: "apis#repo1"
    get "/api/v1/all", to: redirect("/api/v1/repos")
  end

  get "/category",                to: redirect("/categories")
  get "/category/:id",            to: redirect("/categories")
  get "/changes",                 to: redirect("/freshest")
  get "/howto",                   to: redirect("/pages/howto")
  get "/users/:login",            to: redirect("/contributors/%{login}")

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :addons, through: :categorizations do
    def cache_key
      [count(:updated_at),maximum(:updated_at)].map(&:to_i).join('-')
    end
  end

  has_many :categorizations, inverse_of: :category

  scope :having_addons, -> {
    select("categories.*, lower(categories.name) as sort_name")
      .joins(:addons)
      .order("lower(categories.name) ASC")
      .uniq
  }

  def to_param
    "#{id} #{name}".parameterize
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  layout "categories"

  before_action :set_category, only: [:show]
  before_filter :set_sidebar

  # GET /repos
  def index
    @categories = Category.joins(:addons)
      .includes(:addons)
      .order("lower(categories.name) ASC, lower(repos.name) ASC")
      .all

    expires_in 6.hours, public: true
    fresh_when last_modified: @categories.maximum(:updated_at)
  end

  # GET /repos/1
  def show
    expires_in 6.hours, public: true
    fresh_when etag: @category
  end

  # # GET /repos/1/edit
  # def edit
  # end

  # # POST /repos
  # def create
  #   @repo = Repo.new(repo_params)

  #   if @repo.save
  #     redirect_to @repo, notice: 'Repo was successfully created.'
  #   else
  #     render :new
  #   end
  # end

  # # PATCH/PUT /repos/1
  # def update
  #   if @repo.update(repo_params)
  #     redirect_to @repo, notice: 'Repo was successfully updated.'
  #   else
  #     render :edit
  #   end
  # end

  # # DELETE /repos/1
  # def destroy
  #   @repo.destroy
  #   redirect_to repos_url, notice: 'Repo was successfully destroyed.'
  # end

  private

  def set_category
    @category = Category
      .joins(:addons)
      .includes(:addons)
      .order("lower(repos.name) ASC")
      .find(params[:id])
  end

  def set_sidebar
    @sidebar_categories = Category.having_addons
  end

end

app/views/categories/_category.slim
- cache([category, category.addons]) do
  - present(category) do |c|
    .row
      .col-md-12
        h2.page-header
          = c.to_s
    - category.addons.each_slice(3) do |addons|
      .row
        = render(partial: "repos/repo", collection: addons)

app/views/categories/_form.html.erb
<%= form_for(@repo) do |f| %>
  <% if @repo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repo.errors.count, "error") %> prohibited this repo from being saved:</h2>

      <ul>
      <% @repo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_sidebar.slim
h4 Categories
ul.nav.sidenav.sidenav-categories
  - categories.each do |category|
    - present(category) do |c|
      li
        = link_to(h(category.name), category_path(category))
        .counts
          = c.categorizations_count

app/views/categories/edit.html.erb
<h1>Editing repo</h1>

<%= render 'form' %>

<%= link_to 'Show', @repo %> |
<%= link_to 'Back', repos_path %>

app/views/categories/index.html.slim
- categories = @categories.map { |c| present(c) }

- categories.each do |c|
  - cache(c) do
    .row
      .col-md-12
        = c.anchor_tag
        h2.page-header
          = c.anchor_link
    - c.addons.each_slice(3) do |addons|
      .row
        = render(partial: "repos/repo", collection: addons)

- content_for(:sidebar) do
  h4 Categories
  ul.nav.sidenav.sidenav-categories
    - categories.each do |c|
      li
        = c.anchor_link

app/views/categories/index.slim
= render(partial: "categories/category", collection: @categories)

app/views/categories/show.slim
= render @category