config/routes.rb
Rails.application.routes.draw do

  root to: redirect('/categories')

  resources :addons,       only: [:index, :show]
  resources :categories,   only: [:index, :show]
  resources :contributors, controller: 'users', only: [:index]

  get "contributors/:login",      to: "users#show",                        as: :contributor
  get "freshest",                 to: "addons#index",    sort: "freshest", as: :freshest
  get "popular",                  to: "addons#index",    sort: "popular",  as: :popular
  get "unsorted",                 to: "unsorteds#index",                   as: :unsorted

  get "/auth/:provider/callback", to: "sessions#create"
  get "/logout",                  to: "sessions#destroy",                  as: :logout

  namespace :admin do
    resources :repos, only: [:index, :update]
  end

  constraints(format: 'json') do
    get "/api/v1/search", to: "apis#search1"
    get "/api/v1/users/:login", to: "apis#user1"
    get "/api/v1/users/:login/repos", to: "apis#user_repos1"
    get "/api/v1/users/:login/repos/:repo_name", to: "apis#user_repo1"
    get "/api/v1/repos", to: "apis#repos1"
    get "/api/v1/repos/:repo_name", to: "apis#repo1"
    get "/api/v1/all", to: redirect("/api/v1/repos")
  end

  get "/category",                to: redirect("/categories")
  get "/category/:id",            to: redirect("/categories")
  get "/changes",                 to: redirect("/freshest")
  get "/howto",                   to: redirect("/pages/howto")
  get "/users/:login",            to: redirect("/contributors/%{login}")

end

app/models/repo.rb
class Repo < ActiveRecord::Base

  REPO_TYPES = %w(addon deleted empty incomplete non_addon repo unsorted)
  SORT_ATTRS = %w(description example_count full_name has_makefile name pushed_at stargazers_count)

  has_many :categories, -> { uniq }, through: :categorizations do
    def cache_key
      [count(:updated_at),maximum(:updated_at)].map(&:to_i).join('-')
    end
  end

  has_many :categorizations
  belongs_to :user, inverse_of: :repos

  validates :type, inclusion: { in: REPO_TYPES.map(&:camelize) }

  # find currently open issues on the repo whose title
  # matches one of our tags. Wish we could do this with labels
  # but it looks like only repo owners can apply labels to issues
  #
  # Current labels: ofx-incomplete, ofx-osx, ofx-win, ofx-linux
  #     (the OS-specific ones indicate a problem on that OS)
  def warning_labels
    @warning_labels ||= begin
      our_labels = ["ofx-incomplete", "ofx-osx", "ofx-win", "ofx-linux"]
      relevant_labels = []
      if issues
        JSON.parse(issues).select{|issue| issue["state"] == "open"  }.each do |issue|
          our_labels.each do |l|
            if Regexp.new(l) =~ issue["title"]
              relevant_labels << l
            end
          end
        end
      end
      relevant_labels
    end
  end

end

app/controllers/admin/repos_controller.rb
class Admin::ReposController < Admin::ApplicationController

  before_action :set_type_counts

  def index
    type = case params[:type]
           when "addon"
             Addon
           when "deleted"
             Deleted
           when "empty"
             Empty
           when "incomplete"
             Incomplete
           when "non_addon"
             NonAddon
           else
             [Unsorted, Incomplete]
           end

    @repos = Repo.where(type: type).order('repos.pushed_at DESC')

    # collections array of categories for generating the categories modal form
    @categories = Category.order("lower(categories.name) ASC").all.map {|c| [c.name, c.id]}

    # HACK: if I put Addon.new() here then the form submit method is
    #       forced to POST by the rails internals. We'll replace the
    #       guts of this object before we post back to the server.
    @placeholder_repo = Repo.new
  end

  def update
    raise "ajax only!" unless request.xhr?

    repo = Repo.includes(:categories).find(repo_id)
    repo.type = repo_type

    # calculate which categories need their fragment caches expired
    affected_category_ids   = []
    unaffected_category_ids = []

    if repo.type == "Addon"
      unaffected_category_ids = repo.category_ids & repo_category_ids
      affected_category_ids = (repo.category_ids + repo_category_ids - unaffected_category_ids).uniq
    end

    repo.category_ids = repo_category_ids

    if repo.save
      # expire the fragment caches for the affected categories
      affected_category_ids.each do |category_id|
        Category.find(category_id).touch
      end

      render(json: {
               status: 200,
               controller: params[:controller],
               action: params[:action],
               repo: {
                 id: repo.id,
                 type: repo.type,
                 type_title: repo.type.titleize
               }
             }, status: :ok)
    else
      render(json: {
               status: 400,
               error: repo.errors.full_messages,
               controller: params[:controller],
               action: params[:action],

             }, status: :bad_request)
    end
  end

  private

  def repo_category_ids
    @repo_category_ids ||= begin
      if repo_params[:category_ids]
        repo_params[:category_ids].map(&:to_i) - [0]
      else
        []
      end
    end
  end

  def repo_id
    params.require(:id)
  end

  def repo_params
    params.require(:repo)
  end

  # TODO: probably we should validate the type...
  def repo_type
    repo_params[:type].camelize
  end

  # dynamically define instace variables for counts of each repo type
  def set_type_counts
    vars = ""
    Repo::REPO_TYPES.each do |t|
      vars << "@#{t}_count = #{t.camelize.constantize}.count;"
    end
    eval(vars)
  end

end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/admin/repos/_repo.slim
- present(repo) do |r|
  tr id="tr_repo_id_#{r.id}"
    td.repo-type data-type=r.type.downcase
      = r.type.titleize
    td.repo-name data-container="body" data-toggle="tooltip" title="#{r.name}"
      = link_to(r.name, r.github_url)
    - if r.user
      - present(r.user) do |u|
        td.maintainer data-container="body" data-toggle="tooltip" title="#{u.login}"
          = u.to_s
    - else
      td.maintainer data-container="body" data-toggle="tooltip" title=""
    td.pushed-at data-order=r.pushed_at('%s')
      abbr.timeago title=r.pushed_at('%Y-%m-%dT%H:%M:%S%z')
        = r.pushed_at("%m/%e/%y")
    td.stargazers-count
      = r.stargazers_count
    td.example-count
      = r.example_count
    td.makefile data-search=r.has_makefile
      - if r.makefile?
        = icon("fas", "file")
    / td.description data-container="body" data-toggle="tooltip" title="#{r.description}"
    /     = r.description
    td.actions
      / this link gets intercepted in application.coffee and it's patch info is injected into the modal for submission
      = link_to("addon", admin_repo_path(repo, type: :addon), data: { repo_id: r.id }, class: 'js-categorize btn btn-xs btn-default')

      - [["delete", :deleted], ["incomplete", :incomplete], ["non addon", :non_addon]].each do |label, type|
        = link_to(label, admin_repo_path(repo, repo:{ type: type }), remote: true, method: :patch, class: 'btn btn-xs btn-default')

app/views/admin/repos/index.slim
table.table.table-bordered.table-striped.repos.js-data-table
  thead
    tr
      th.repo-type
        div
          span Type
      th.repo-name
        div
          span Name
      th.maintainer
        div
          span Maintainer
      th.pushed-at
        div
          span Last Update
      th.stargazers-count
        div
          span Stars
      th.example-count
        div
          span Examples
      th.makefile
        div
          span Makefile
      / th.description
      /   div
      /     span Description
      th.actions
        div
          span Set Type
  tbody
    = render(partial: "admin/repos/repo", collection: @repos)

#categorize_modal.modal.fade
  .modal-dialog
    .modal-content
      = simple_form_for(@placeholder_repo, url: "#", data:{ url_base: admin_repos_path }, method: :patch, remote: true) do |f|
        .modal-header
          button type="button" class="close" data-dismiss="modal" aria-label="Close"
            span aria-hidden="true"
              | &times;
          h4 class="modal-title"
            | Categories
        .modal-body
          .row
            = f.input_field(:id,   as: :hidden)
            = f.input_field(:type, as: :hidden)
            = f.association(:categories, as: :check_boxes, collection: @categories)

        .modal-footer
          button type="button" class="btn btn-default" data-dismiss="modal"
            | Close
          = f.button(:submit, "Save")