config/routes.rb
Rails.application.routes.draw do

  root to: redirect('/categories')

  resources :addons,       only: [:index, :show]
  resources :categories,   only: [:index, :show]
  resources :contributors, controller: 'users', only: [:index]

  get "contributors/:login",      to: "users#show",                        as: :contributor
  get "freshest",                 to: "addons#index",    sort: "freshest", as: :freshest
  get "popular",                  to: "addons#index",    sort: "popular",  as: :popular
  get "unsorted",                 to: "unsorteds#index",                   as: :unsorted

  get "/auth/:provider/callback", to: "sessions#create"
  get "/logout",                  to: "sessions#destroy",                  as: :logout

  namespace :admin do
    resources :repos, only: [:index, :update]
  end

  constraints(format: 'json') do
    get "/api/v1/search", to: "apis#search1"
    get "/api/v1/users/:login", to: "apis#user1"
    get "/api/v1/users/:login/repos", to: "apis#user_repos1"
    get "/api/v1/users/:login/repos/:repo_name", to: "apis#user_repo1"
    get "/api/v1/repos", to: "apis#repos1"
    get "/api/v1/repos/:repo_name", to: "apis#repo1"
    get "/api/v1/all", to: redirect("/api/v1/repos")
  end

  get "/category",                to: redirect("/categories")
  get "/category/:id",            to: redirect("/categories")
  get "/changes",                 to: redirect("/freshest")
  get "/howto",                   to: redirect("/pages/howto")
  get "/users/:login",            to: redirect("/contributors/%{login}")

end

app/views/layouts/admin.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title
      = content_for(:title) || "ofxaddons.com"
    link href="http://fonts.googleapis.com/css?family=Questrial" rel="stylesheet" type="text/css"
    = stylesheet_link_tag('admin', media: 'all')
    = javascript_include_tag('admin')
    = csrf_meta_tags
    
    / HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"
      script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"
  body id=@action
    nav class="navbar navbar-default navbar-fixed-top" role="navigation"
      .container
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to(root_path, class: "navbar-brand") do
            = image_tag("ofxlogo-small.png", size: "37x24", alt: "ofxAddons logo", class: "navbar-brand-logo")
            | ofxAddons

        / Collect the nav links, forms, and other content for toggling
        #navbar.navbar-collapse.collapse
          ul.nav.navbar-nav
            li = link_to("categories", categories_path)
            li = link_to("popular", popular_path)
            li = link_to("freshest", freshest_path)
            li = link_to("unsorted", unsorted_path)
            li = link_to("contributors", contributors_path)
            li = link_to("faq/help", page_path("howto"))
            li.admin.hidden = link_to("admin", admin_repos_path)

          / form class="navbar-form navbar-right" role="search"
          /   .form-group
          /     input.form-control type="text" placeholder="Search"

          ul.nav.navbar-nav
            li.current-user.hidden
            li.logout.hidden = link_to("logout", logout_path)
            li.login = link_to("/auth/github") do
              = icon("fab", "github")
              | &nbsp;login

    .container-fluid
      .row
        .col-md-12
          = flash_messages
          = content_for?(:content) ? yield(:content) : yield

    = yield(:script)

    - unless ENV["GOOGLE_ANALYTICS_ID"].blank?
      javascript:
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', '#{ ENV["GOOGLE_ANALYTICS_ID"] }', 'auto');
        ga('send', 'pageview');

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title
      = content_for(:title) || "ofxaddons.com"
    link href="http://fonts.googleapis.com/css?family=Questrial" rel="stylesheet" type="text/css"
    = stylesheet_link_tag('application', media: 'all')
    = javascript_include_tag('application')
    = csrf_meta_tags
    = yield(:head)
    
    / HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"
      script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"
  body id=@action
    nav class="navbar navbar-default navbar-fixed-top" role="navigation"
      .container
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to(root_path, class: "navbar-brand") do
            = image_tag("ofxlogo-small.png", size: "37x24", alt: "ofxAddons logo", class: "navbar-brand-logo")
            | ofxAddons

        / Collect the nav links, forms, and other content for toggling
        #navbar.navbar-collapse.collapse
          ul.nav.navbar-nav
            li = link_to("categories", categories_path)
            li = link_to("popular", popular_path)
            li = link_to("freshest", freshest_path)
            li = link_to("unsorted", unsorted_path)
            li = link_to("contributors", contributors_path)
            li = link_to("faq/help", page_path("howto"))
            li.admin.hidden = link_to("admin", admin_repos_path)

          / form class="navbar-form navbar-right" role="search"
          /   .form-group
          /     input.form-control type="text" placeholder="Search"

          ul.nav.navbar-nav
            li.current-user.hidden
            li.logout.hidden = link_to("logout", logout_path)
            li.login = link_to("/auth/github") do
              = icon("fab", "github")
              | &nbsp;login

    .container
      .row
        .sidebar.col-md-2
          .affixed
            = yield(:sidebar)

        .col-md-10
          = flash_messages
          .well
            | ofxAddons is directory of extensions and libraries for the #{ link_to("openFrameworks", "http://openframeworks.cc") } creative coding toolkit. Compiled fresh from #{ link_to("Github", "http://github.com") } daily.
          = content_for?(:content) ? yield(:content) : yield

    = yield(:script)

    - unless ENV["GOOGLE_ANALYTICS_ID"].blank?
      javascript:
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', '#{ ENV["GOOGLE_ANALYTICS_ID"] }', 'auto');
        ga('send', 'pageview');

app/views/layouts/categories.slim
- content_for(:sidebar) do
  = render(partial: "categories/sidebar", locals: { categories: @sidebar_categories })

- content_for(:content) do
  = yield

= render template: "layouts/application"